name: Android CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Functional Testing fudi-annotation
        run: wget --quiet --output-document=android-wait-for-emulator https://raw.githubusercontent.com/travis-ci/travis-cookbooks/0f497eb71291b52a703143c5cd63a217c8766dc9/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
        run: chmod +x android-wait-for-emulator
        run: echo y | android-sdk-linux/tools/android update sdk --no-ui --all --filter sys-img-x86-google_apis-26
        run: echo no | android-sdk-linux/tools/android create avd -n test -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86
        run: android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
        run: ./android-wait-for-emulator
        run: adb shell input keyevent 82
        run: /gradlew cAT
      - name: Upload Testing fudi-annotation
        uses: actions/upload-artifact@v1
        with:
          name: fudi-annotation-test
          path: fudi-annotation/build/reports/tests/testDebugUnitTest
      - name: Upload fudi-annotation artifact
        uses: actions/upload-artifact@v1
        with:
          name: fudi-annotation-aar
          path: fudi-annotation/build/outputs/aar/fudi-annotation-debug.aar
          