name: Android CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Testing fudi-annotation
        run: ./gradlew assembleDebug lint testDebugUnitTest -p fudi-annotation
      - name: Upload Testing fudi-annotation
        uses: actions/upload-artifact@v1
        with:
          name: fudi-annotation-test
          path: fudi-annotation/build/reports/tests/testDebugUnitTest
      - name: Upload fudi-annotation artifact
        uses: actions/upload-artifact@v1
        with:
          name: fudi-annotation-aar
          path: fudi-annotation/build/outputs/aar/fudi-annotation-debug.aar
          